### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by princemaple**
fix typo or copy paste leftover

### CODE REVIEW

**Comment by swelham** [comment]
Thanks for the PR @princemaple, well spotted :+1:

**Comment by princemaple** [comment]
:)

Question for you, hope you don't mind me reusing this PR

How are you supposed to use this package?
I mean, it's good to be able to extract the information, but it's not as useful if you don't have the context.
I was thinking maybe you can parse the text into something like

``` elixir
[
  "Hi ", # this or {:text, "Hi "}
  {:mention, "@you"},
  "check out ",
  {:link, "http://example.com/"},
  " that ",
  {:mention, "+someone"},
  " hosted ",
  {:tag, "#examples"}
]
```

in addition to the `%{...}` of all the extracted information?

**Comment by swelham** [comment]
My initial use of this package was for a small project that I was working on where I needed to extract the mentions, hashtags and links out of a description about a photo.

So I was doing something like this in my web app (psudocode)

``` elixir
def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:description])
    |> validate_required([:description])
    |> parse_social_components()
end

defp parse_social_components(changeset) do
    components = SocialParser.parse(changeset.description)

    put_change(changeset, :tags, components.tags)
    # handles other components...
end
```

So at this point I was only really interested in the components I was targeting.

I really like your idea, I would probably favor the approach that includes `{:text, "Hi "}` for a more consistent feel. Maybe this should be the return value for the `parse` function and there should be another function that allows returning the map as this more easily supports the use case above.

**Comment by princemaple** [comment]
Yep, with this form

``` elixir
[
  {:text, "Hi "},
  {:mention, "@you"},
  ...
]
```

You can do `Enum.group_by(parsed_data, &elem(&1, 0))` to get the map.
If you only care about one type you can do `Enum.filter`
And it's really easy to write a function to render the parsed data into HTML or something else.

**Comment by swelham** [comment]
Great idea! I think I might consider adding a convenience function that will internally call `parse` and then do the group/filter based on a provided list of atoms.

Something along the lines of this

``` elixir
SocialParser.parse_components(message, [:hashtags, :mentions])
# %{hashtags: [...], mentions: [...]}
```

Edit: Also I have added [gitter room](https://gitter.im/social_parser/Lobby) for this repo which should make it easier to chat

**Pull request merged**
